version: '3.7'

services:
  database:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bugzot_admin
      - POSTGRES_PASSWORD=bugzotuser
      - POSTGRES_DB=bugzot
    volumes:
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5435:5432"

  webserver:
    image: bugzot:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///bugzot.db
      - POSTGRES_USER=bugzot_admin
      - POSTGRES_PASSWORD=bugzotuser
      - POSTGRES_DB=bugzot
    command: webserver

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=bugzot
      - POSTGRES_USERNAME=bugzot_admin
      - POSTGRES_PASSWORD=bugzotuser
    ports:
      - "5050:80"

  reverse-proxy:
    image: nginx:1.11
    volumes:
      - ./reverse-proxy/bugzot.conf:/etc/nginx/conf.d/bugzot.conf
    ports:
      - "33000:80"