FROM bugzot-base:latest
COPY ./requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN apt update -y && apt upgrade -y  && apt install -y libcairo2-dev libgirepository1.0-dev
RUN pip install -r requirements.txt
